"""Phase 9C bounded three-calendar-day real-backend preflight.

This module is intentionally a thin MarketLens orchestration layer around already
frozen/inherited behavior. It does not implement matching, price formation,
Agent portfolio updates, TradingDetails generation, or alternative Agent
reasoning.

The fixed Phase 9C v1.0 engineering contract is:

* N = 10, generated by the frozen Phase 3 population builder;
* 2023-06-15 through 2023-06-17 (two authoritative open days + one closed day);
* frozen Phase 4 activation with carried recency state;
* Phase 6 bounded graph + deterministic prominence recomputed each day;
* inherited ``simulation.process_user_input`` for each active Agent;
* Phase 7 inherited market wrappers for open/closed days;
* inherited ForumDB post/action/score functions;
* no participant input and no structured-output/inference monkeypatching.

The small belief adapter below mirrors the exact fallback orchestration that
exists inside inherited ``simulation.init_simulation``. Calling that whole
function is unsafe for MarketLens because it owns global Agent enumeration and
its own activation draw, which would bypass frozen Phase 3/4. The actual forum
belief source remains inherited ``get_all_users_posts_db``.
"""

from __future__ import annotations

import asyncio
import dataclasses
import hashlib
import json
import shutil
import sqlite3
import subprocess
import sys
import tempfile
import time
from collections.abc import Callable, Iterable, Mapping, Sequence
from datetime import date, datetime, timedelta, timezone
from pathlib import Path
from typing import Any

import pandas as pd


PHASE09C_VERSION = "marketlens_phase09c_n10_multiday_preflight/1.0"
BANNER = (
    "NON-FORMAL / N10 MULTI-DAY REAL-BACKEND PREFLIGHT / "
    "NOT FORMAL EXPERIMENT EVIDENCE"
)
DRY_BANNER = (
    "NON-FORMAL / N10 MULTI-DAY DRY RUN / 0 LLM / "
    "NOT FORMAL EXPERIMENT EVIDENCE"
)
POPULATION_SIZE = 10
POPULATION_SEED = "marketlens-phase09c-n10-population-01"
ACTIVATION_SEED = "marketlens-phase09c-n10-activation-01"
START_DATE = date(2023, 6, 15)
END_DATE = date(2023, 6, 17)
EXPECTED_DATES = ("2023-06-15", "2023-06-16", "2023-06-17")
EXPECTED_MARKET_OPEN = (True, True, False)
GRAPH_START_DATE = "2023-01-01"
SIMILARITY_THRESHOLD = 0.1
TIME_DECAY_FACTOR = 0.05
TOP_FRACTION = 0.1
PROB_OF_TECHNICAL = 0.0


class Phase09CError(RuntimeError):
    """Raised when the bounded Phase 9C contract cannot be executed safely."""


def fixed_dates() -> tuple[str, ...]:
    """Return the hard-limited three-calendar-day Phase 9C horizon."""
    current = START_DATE
    result: list[str] = []
    while current <= END_DATE:
        result.append(current.isoformat())
        current += timedelta(days=1)
    if tuple(result) != EXPECTED_DATES:
        raise Phase09CError("internal Phase 9C date contract drifted")
    return tuple(result)


def sha256_file(path: str | Path) -> str:
    digest = hashlib.sha256()
    with Path(path).open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _json_digest(value: Any) -> str:
    payload = json.dumps(
        value,
        sort_keys=True,
        ensure_ascii=False,
        separators=(",", ":"),
        default=str,
    ).encode("utf-8")
    return hashlib.sha256(payload).hexdigest()


def activation_state_digest(state: Any | None) -> str | None:
    """Digest the frozen Phase 4 recency mapping without mutating it."""
    if state is None:
        return None
    mapping = getattr(state, "steps_since_last_activation", None)
    if mapping is None:
        raise Phase09CError("activation state has no steps_since_last_activation mapping")
    normalized = {str(k): int(v) for k, v in sorted(mapping.items(), key=lambda item: str(item[0]))}
    return _json_digest(normalized)


def make_activation_mapping(
    population_ids: Sequence[str], active_ids: Sequence[str]
) -> dict[str, bool]:
    population = tuple(str(item) for item in population_ids)
    active = {str(item) for item in active_ids}
    unknown = sorted(active - set(population))
    if unknown:
        raise Phase09CError(f"active Agent(s) outside bounded N10 population: {unknown}")
    return {user_id: user_id in active for user_id in population}


def build_forum_belief_args(
    *,
    forum_db: str | Path,
    current_date: pd.Timestamp,
    initial_beliefs: pd.DataFrame,
    population_ids: Sequence[str],
    forum_reader: Callable[..., Any],
) -> tuple[dict[str, list[dict[str, Any]]], dict[str, int]]:
    """Use inherited forum beliefs, with inherited initial-belief fallback.

    This is the minimum adaptation needed because ``simulation.init_simulation``
    cannot be used wholesale without bypassing Phase 3 bounded membership and
    Phase 4 activation. The logic intentionally follows the inherited source:
    forum first; missing/no-belief rows fall back to the initial belief CSV.
    """
    raw = forum_reader(db_path=str(forum_db), end_date=current_date)
    belief_args: dict[str, Any]
    if isinstance(raw, dict):
        belief_args = {str(k): v for k, v in raw.items()}
    else:
        belief_args = {}

    df_belief = initial_beliefs.copy()
    if "user_id" not in df_belief.columns or "belief" not in df_belief.columns:
        raise Phase09CError("initial belief frame must contain user_id and belief")
    df_belief["user_id"] = df_belief["user_id"].astype(str)

    forum_with_belief = 0
    fallback_no_post = 0
    fallback_missing_belief = 0

    for uid in (str(item) for item in population_ids):
        posts = belief_args.get(uid)
        has_belief = (
            isinstance(posts, list)
            and len(posts) > 0
            and isinstance(posts[0], dict)
            and "belief" in posts[0]
        )
        if has_belief:
            forum_with_belief += 1
            continue

        series = df_belief.loc[df_belief["user_id"] == uid, "belief"]
        if series.empty:
            raise Phase09CError(f"no initial belief available for bounded Agent {uid}")
        belief_args[uid] = [{"belief": series.iloc[0]}]
        if not posts:
            fallback_no_post += 1
        else:
            fallback_missing_belief += 1

    normalized: dict[str, list[dict[str, Any]]] = {}
    for key, value in belief_args.items():
        if isinstance(value, list):
            normalized[str(key)] = value

    missing = sorted(set(map(str, population_ids)) - set(normalized))
    if missing:
        raise Phase09CError(f"belief mapping incomplete after fallback: {missing}")

    return normalized, {
        "population": len(population_ids),
        "forum_with_belief": forum_with_belief,
        "fallback_no_post": fallback_no_post,
        "fallback_missing_belief": fallback_missing_belief,
    }


def _sqlite_columns(conn: sqlite3.Connection, table: str) -> tuple[str, ...]:
    rows = conn.execute(f'PRAGMA table_info("{table}")').fetchall()
    return tuple(str(row[1]) for row in rows)


def _count_for_date(
    conn: sqlite3.Connection, table: str, column: str, current_date: str
) -> int | None:
    columns = _sqlite_columns(conn, table)
    if column not in columns:
        return None
    query = (
        f'SELECT COUNT(*) FROM "{table}" '
        f'WHERE substr(CAST("{column}" AS TEXT), 1, 10) = ?'
    )
    return int(conn.execute(query, (current_date,)).fetchone()[0])


def capture_runtime_metrics(runtime_db: str | Path, current_date: str) -> dict[str, Any]:
    """Read only post-day continuity metrics from the isolated runtime DB."""
    with sqlite3.connect(str(runtime_db)) as conn:
        tables = {
            row[0]
            for row in conn.execute(
                "SELECT name FROM sqlite_master WHERE type='table'"
            ).fetchall()
        }
        required = {"Profiles", "StockData", "TradingDetails"}
        missing = sorted(required - tables)
        if missing:
            raise Phase09CError(f"runtime DB missing inherited table(s): {missing}")

        result: dict[str, Any] = {}
        date_cols = {
            "Profiles": "created_at",
            "StockData": "date",
            "TradingDetails": "created_at",
        }
        for table in ("Profiles", "StockData", "TradingDetails"):
            total = int(conn.execute(f'SELECT COUNT(*) FROM "{table}"').fetchone()[0])
            result[table] = {
                "total_rows": total,
                "rows_for_date": _count_for_date(
                    conn, table, date_cols[table], current_date
                ),
            }
        return result


def capture_forum_metrics(forum_db: str | Path) -> dict[str, int]:
    with sqlite3.connect(str(forum_db)) as conn:
        tables = {
            row[0]
            for row in conn.execute(
                "SELECT name FROM sqlite_master WHERE type='table'"
            ).fetchall()
        }
        result: dict[str, int] = {}
        for table in ("posts", "reactions", "post_references"):
            result[table] = (
                int(conn.execute(f'SELECT COUNT(*) FROM "{table}"').fetchone()[0])
                if table in tables
                else 0
            )
        return result


def write_daily_records(
    *,
    log_dir: str | Path,
    current_date: str,
    agent_results: Sequence[Mapping[str, Any]],
) -> dict[str, str]:
    """Write the same three day-level record families used by TwinMarket."""
    root = Path(log_dir)
    families = {
        "trading_records": "decision_result",
        "reaction_records": "forum_args",
        "post_records": "post_response_args",
    }
    written: dict[str, str] = {}
    for folder, field in families.items():
        target_dir = root / folder
        target_dir.mkdir(parents=True, exist_ok=True)
        target = target_dir / f"{current_date}.json"
        payload = {
            str(item["user_id"]): item.get(field)
            for item in agent_results
        }
        target.write_text(
            json.dumps(payload, indent=4, ensure_ascii=False, default=str),
            encoding="utf-8",
        )
        written[folder] = str(target)
    return written


def _serialize_result(value: Any) -> Any:
    if dataclasses.is_dataclass(value):
        return dataclasses.asdict(value)
    if isinstance(value, Mapping):
        return dict(value)
    if hasattr(value, "__dict__"):
        return {
            str(key): item
            for key, item in vars(value).items()
            if not str(key).startswith("_")
        }
    return repr(value)


def _git(repo_root: Path, *args: str) -> str:
    completed = subprocess.run(
        ["git", *args],
        cwd=repo_root,
        check=True,
        capture_output=True,
        text=True,
    )
    return completed.stdout.strip()


def git_state(repo_root: str | Path) -> dict[str, Any]:
    root = Path(repo_root).resolve()
    return {
        "commit": _git(root, "rev-parse", "HEAD"),
        "branch": _git(root, "branch", "--show-current"),
        "status_porcelain": _git(root, "status", "--porcelain"),
    }


def _ensure_real_run_clean(repo_root: Path) -> dict[str, Any]:
    state = git_state(repo_root)
    if state["status_porcelain"]:
        raise Phase09CError(
            "real-backend Phase 9C requires a clean Git working tree; "
            "commit/stash intended code changes first"
        )
    return state


def _generate_fixture(
    *, repo_root: Path, source_db: Path, fixture_dir: Path
) -> tuple[Path, Path, str]:
    # Phase 3 runtime_cli owns creation of its output directory.  Do not create
    # ``fixture_dir`` here: the frozen builder intentionally fails if the
    # requested output directory already exists.
    fixture_dir.parent.mkdir(parents=True, exist_ok=True)
    if fixture_dir.exists():
        raise Phase09CError(
            f"Phase 9C fixture output directory already exists: {fixture_dir}"
        )

    command = [
        sys.executable,
        "-m",
        "marketlens.agents.population.runtime_cli",
        "--source-db",
        str(source_db),
        "--population-size",
        str(POPULATION_SIZE),
        "--seed",
        POPULATION_SEED,
        "--output-dir",
        str(fixture_dir),
    ]
    try:
        completed = subprocess.run(
            command,
            cwd=repo_root,
            check=True,
            capture_output=True,
            text=True,
        )
    except subprocess.CalledProcessError as exc:
        stdout = (exc.stdout or "").strip()
        stderr = (exc.stderr or "").strip()
        details = []
        if stdout:
            details.append(f"stdout:\n{stdout}")
        if stderr:
            details.append(f"stderr:\n{stderr}")
        suffix = "\n" + "\n".join(details) if details else ""
        raise Phase09CError(
            "frozen Phase 3 runtime_cli failed while generating the N10 "
            f"fixture (exit {exc.returncode}).{suffix}"
        ) from exc

    runtime_db = fixture_dir / "population_runtime.db"
    manifest = fixture_dir / "population_manifest.json"
    if not runtime_db.is_file() or not manifest.is_file():
        raise Phase09CError(
            "frozen Phase 3 runtime_cli did not create expected N10 fixture files"
        )
    return runtime_db, manifest, completed.stdout


def _protected_hashes(paths: Mapping[str, Path]) -> dict[str, str]:
    missing = [name for name, path in paths.items() if not path.is_file()]
    if missing:
        raise Phase09CError(f"missing protected source file(s): {missing}")
    return {name: sha256_file(path) for name, path in paths.items()}


def _load_config_public(config_path: Path) -> dict[str, Any]:
    import yaml

    if not config_path.is_file():
        raise Phase09CError(f"API config not found: {config_path}")
    doc = yaml.safe_load(config_path.read_text(encoding="utf-8")) or {}
    if not isinstance(doc, dict):
        raise Phase09CError("API config must be a mapping")
    return {
        "path": str(config_path),
        "model_name": doc.get("model_name"),
        "base_url": doc.get("base_url"),
        "api_key_configured": bool(doc.get("api_key")),
    }


def _prepare_activation_batches(runtime_db: Path) -> tuple[tuple[Any, ...], tuple[dict[str, Any], ...]]:
    from marketlens.agents.activation.policy import ActivationPolicy
    from marketlens.agents.activation.profiles import load_activation_profiles
    from marketlens.agents.activation.sampler import sample_activation

    profiles = load_activation_profiles(runtime_db)
    if len(profiles) != POPULATION_SIZE:
        raise Phase09CError(
            f"Phase 9C requires N10; activation profile count is {len(profiles)}"
        )
    policy = ActivationPolicy()
    state = None
    batches: list[Any] = []
    evidence: list[dict[str, Any]] = []
    for step, current_date in enumerate(fixed_dates()):
        input_digest = activation_state_digest(state)
        batch = sample_activation(
            profiles,
            policy=policy,
            state=state,
            seed=ACTIVATION_SEED,
            step=step,
        )
        output_digest = activation_state_digest(batch.next_state)
        batches.append(batch)
        evidence.append(
            {
                "step": step,
                "agent_world_date": current_date,
                "active_agent_ids": list(map(str, batch.active_agent_ids)),
                "n_active": len(batch.active_agent_ids),
                "input_state_digest": input_digest,
                "output_state_digest": output_digest,
                "policy_version": getattr(batch, "policy_version", None),
            }
        )
        state = batch.next_state
    return tuple(batches), tuple(evidence)


def _load_runtime_frames(runtime_db: Path, *, market_open: bool) -> tuple[pd.DataFrame | None, pd.DataFrame]:
    with sqlite3.connect(str(runtime_db)) as conn:
        df_strategy = pd.read_sql_query("SELECT * FROM Strategy;", conn)
        df_strategy["user_id"] = df_strategy["user_id"].astype(str)
        if market_open:
            df_stock = pd.read_sql_query("SELECT * FROM StockData;", conn)
            if "date" in df_stock.columns:
                df_stock["date"] = pd.to_datetime(df_stock["date"])
        else:
            df_stock = None
    return df_stock, df_strategy


def _execute_active_agents(
    *,
    process_user_input_fn: Callable[..., Any],
    population_ids: Sequence[str],
    active_ids: Sequence[str],
    runtime_db: Path,
    forum_db: Path,
    current_date: pd.Timestamp,
    day_1st: bool,
    graph: Any,
    news_items: list[Any],
    df_stock: pd.DataFrame | None,
    df_strategy: pd.DataFrame,
    top_user_ids: Sequence[str],
    belief_args: Any,
    log_dir: Path,
    config_path: Path,
    market_open: bool,
) -> list[dict[str, Any]]:
    activation_mapping = make_activation_mapping(population_ids, active_ids)
    config_mapping = {str(uid): str(config_path) for uid in population_ids}
    results: list[dict[str, Any]] = []

    for user_id in map(str, active_ids):
        started = time.perf_counter()
        returned = process_user_input_fn(
            user_id,
            str(runtime_db),
            str(forum_db),
            df_stock,
            current_date,
            False,
            day_1st,
            graph,
            news_items,
            df_strategy,
            market_open,
            list(map(str, top_user_ids)),
            str(log_dir),
            PROB_OF_TECHNICAL,
            config_mapping,
            activation_mapping,
            belief_args,
            str(config_path),
        )
        elapsed = round(time.perf_counter() - started, 3)
        if not isinstance(returned, tuple) or len(returned) != 4:
            raise Phase09CError(
                f"inherited process_user_input returned invalid shape for Agent {user_id}"
            )
        returned_user_id, forum_args, decision_result, post_response_args = returned
        if str(returned_user_id) != user_id:
            raise Phase09CError(
                f"inherited process_user_input returned mismatched user_id {returned_user_id!r} "
                f"for requested Agent {user_id}"
            )
        inherited_error = None
        if isinstance(forum_args, Mapping) and forum_args.get("error"):
            inherited_error = str(forum_args["error"])
        if inherited_error:
            raise Phase09CError(
                f"inherited Agent reasoning failed for {user_id}: {inherited_error}"
            )
        if market_open and decision_result is None:
            raise Phase09CError(
                f"open-day active Agent {user_id} returned no decision result"
            )
        results.append(
            {
                "user_id": user_id,
                "forum_args": forum_args,
                "decision_result": decision_result,
                "post_response_args": post_response_args,
                "duration_seconds": elapsed,
            }
        )
    return results


def _create_posts(
    *,
    agent_results: Sequence[Mapping[str, Any]],
    current_date: pd.Timestamp,
    forum_db: Path,
    create_post_fn: Callable[..., Any],
) -> dict[str, int]:
    attempted = 0
    created = 0
    skipped_invalid = 0
    for item in agent_results:
        post_args = item.get("post_response_args")
        if not isinstance(post_args, dict):
            skipped_invalid += 1
            continue
        required = ("post", "type", "belief")
        if not all(key in post_args and post_args[key] is not None for key in required):
            skipped_invalid += 1
            continue
        attempted += 1
        create_post_fn(
            user_id=str(item["user_id"]),
            content=post_args["post"],
            type=post_args["type"],
            belief=str(post_args["belief"]),
            created_at=current_date,
            db_path=str(forum_db),
        )
        created += 1
    return {
        "attempted": attempted,
        "created": created,
        "skipped_invalid": skipped_invalid,
    }


def _apply_forum_actions(
    *,
    agent_results: Sequence[Mapping[str, Any]],
    current_date: pd.Timestamp,
    forum_db: Path,
    execute_forum_actions_fn: Callable[..., Any],
    update_scores_fn: Callable[..., Any],
) -> dict[str, Any]:
    attempts = 0
    successful_calls = 0
    skipped_string = 0
    for item in agent_results:
        forum_args = item.get("forum_args")
        if isinstance(forum_args, str):
            skipped_string += 1
            continue
        attempts += 1
        asyncio.run(
            execute_forum_actions_fn(
                forum_args=forum_args,
                db_path=str(forum_db),
                user_id=str(item["user_id"]),
                created_at=current_date,
            )
        )
        successful_calls += 1
    update_scores_fn(
        db_path=str(forum_db),
        end_date=current_date.strftime("%Y-%m-%d"),
    )
    return {
        "attempted_user_calls": attempts,
        "successful_user_calls": successful_calls,
        "skipped_string_args": skipped_string,
        "score_update_invoked": True,
    }


def _day_plan(
    *, trading_days: frozenset[str], news_pickle: Path
) -> list[dict[str, Any]]:
    from marketlens.market.runtime.news import load_daily_news

    days: list[dict[str, Any]] = []
    for step, current_date in enumerate(fixed_dates()):
        open_flag = current_date in trading_days
        days.append(
            {
                "step": step,
                "agent_world_date": current_date,
                "history_cutoff": (
                    datetime.strptime(current_date, "%Y-%m-%d").date() - timedelta(days=1)
                ).isoformat(),
                "day_1st": step == 0,
                "market_open": open_flag,
                "participant_trading_enabled": open_flag,
                "expected_market_action": (
                    "advance_trading_day" if open_flag else "advance_non_trading_day"
                ),
                "background_news_items": len(
                    load_daily_news(news_pickle, current_date=current_date)
                ),
            }
        )
    actual_pattern = tuple(day["market_open"] for day in days)
    if actual_pattern != EXPECTED_MARKET_OPEN:
        raise Phase09CError(
            "Phase 9C fixed horizon no longer resolves to OPEN, OPEN, CLOSED "
            f"under the authoritative calendar: {actual_pattern}"
        )
    return days


def _validate_runtime_day(
    *, metrics: Mapping[str, Any], market_open: bool, population_size: int
) -> list[str]:
    failures: list[str] = []
    profile_rows = metrics["Profiles"].get("rows_for_date")
    if profile_rows != population_size:
        failures.append(
            f"Profiles rows_for_date={profile_rows}, expected bounded population {population_size}"
        )
    if market_open:
        stock_rows = metrics["StockData"].get("rows_for_date")
        if stock_rows is None or stock_rows <= 0:
            failures.append("open day produced no StockData rows for authoritative date")
    return failures


def validate_real_summary(summary: Mapping[str, Any]) -> tuple[str, list[str]]:
    """Return (status, reasons) without hiding natural inconclusive coverage."""
    failures: list[str] = []
    inconclusive: list[str] = []

    if summary.get("population", {}).get("size") != POPULATION_SIZE:
        failures.append("population size is not fixed N10")
    if tuple(summary.get("horizon", {}).get("dates", ())) != EXPECTED_DATES:
        failures.append("calendar horizon drifted")
    if tuple(summary.get("horizon", {}).get("market_open", ())) != EXPECTED_MARKET_OPEN:
        failures.append("authoritative OPEN/OPEN/CLOSED pattern failed")
    if not summary.get("integrity", {}).get("protected_sources_unchanged"):
        failures.append("protected canonical source hash changed")
    if not summary.get("integrity", {}).get("generated_fixture_unchanged"):
        failures.append("generated source fixture was mutated instead of isolated copy")
    if not summary.get("continuity", {}).get("activation_state_chain_valid"):
        failures.append("Phase 4 activation recency state chain is broken")
    if not summary.get("continuity", {}).get("all_graphs_bounded_n10"):
        failures.append("one or more daily graphs did not contain exactly N10 nodes")
    if summary.get("integrity", {}).get("participant_data_used") is not False:
        failures.append("participant data must not enter Phase 9C")
    if summary.get("integrity", {}).get("custom_market_logic_used") is not False:
        failures.append("custom market logic must not be used")

    for day in summary.get("days", []):
        failures.extend(day.get("post_day_validation_failures", []))
        if day.get("reasoning", {}).get("failed_agents", 0) != 0:
            failures.append(
                f"Agent reasoning failure on {day.get('agent_world_date')}"
            )

    natural = summary.get("natural_multiday_coverage", {})
    if natural.get("posts_created_total", 0) <= 0:
        inconclusive.append("no natural Agent post was created across the three-day N10 run")
    if natural.get("forum_belief_agents_observed", 0) <= 0:
        inconclusive.append(
            "no later-day Agent belief was naturally sourced from ForumDB; only initial fallback was exercised"
        )
    if natural.get("later_day_forum_action_calls", 0) <= 0:
        inconclusive.append("no later-day inherited forum-action call was exercised")

    if failures:
        return "FAIL", failures + inconclusive
    if inconclusive:
        return "INCONCLUSIVE_NATURAL_FORUM_BELIEF_COVERAGE", inconclusive
    return "PASS", []


def run_phase09c(
    *,
    repo_root: str | Path,
    source_db: str | Path,
    belief_csv: str | Path,
    config_path: str | Path,
    news_pickle: str | Path,
    trading_calendar: str | Path,
    artifact_root: str | Path,
    execute_real_backend: bool,
    acknowledge_non_formal: bool,
    preserve_workspace: bool = False,
) -> dict[str, Any]:
    """Run the fixed N10 Phase 9C dry run or paid real-backend preflight."""
    root = Path(repo_root).resolve()
    source_db_p = (root / source_db).resolve() if not Path(source_db).is_absolute() else Path(source_db).resolve()
    belief_csv_p = (root / belief_csv).resolve() if not Path(belief_csv).is_absolute() else Path(belief_csv).resolve()
    config_path_p = (root / config_path).resolve() if not Path(config_path).is_absolute() else Path(config_path).resolve()
    news_pickle_p = (root / news_pickle).resolve() if not Path(news_pickle).is_absolute() else Path(news_pickle).resolve()
    trading_calendar_p = (root / trading_calendar).resolve() if not Path(trading_calendar).is_absolute() else Path(trading_calendar).resolve()
    artifact_root_p = (root / artifact_root).resolve() if not Path(artifact_root).is_absolute() else Path(artifact_root).resolve()

    if execute_real_backend and not acknowledge_non_formal:
        raise Phase09CError(
            "--execute-real-backend requires --acknowledge-non-formal"
        )

    start_time = time.perf_counter()
    git = _ensure_real_run_clean(root) if execute_real_backend else git_state(root)
    short_commit = git["commit"][:8]
    mode = "real" if execute_real_backend else "dry"
    run_id = (
        datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
        + f"_{short_commit}_phase09c_n10_{mode}"
    )
    run_dir = artifact_root_p / run_id
    run_dir.mkdir(parents=True, exist_ok=False)

    fixture_dir = run_dir / "population_fixture"
    fixture_db, fixture_manifest, fixture_stdout = _generate_fixture(
        repo_root=root,
        source_db=source_db_p,
        fixture_dir=fixture_dir,
    )
    (run_dir / "fixture_generation_stdout.txt").write_text(
        fixture_stdout, encoding="utf-8"
    )

    from marketlens.agents.runtime.preflight import (
        create_empty_forum_db,
        load_initial_beliefs,
        verify_population_fixture,
    )
    from marketlens.market.runtime.news import load_trading_day_set

    verified = verify_population_fixture(fixture_db, fixture_manifest)
    population_ids = tuple(map(str, verified.population_ids))
    if len(population_ids) != POPULATION_SIZE:
        raise Phase09CError(
            f"frozen Phase 3 generated {len(population_ids)} Agents, expected N10"
        )

    trading_days = load_trading_day_set(trading_calendar_p)
    day_plan = _day_plan(trading_days=trading_days, news_pickle=news_pickle_p)
    batches, activation_plan = _prepare_activation_batches(fixture_db)

    public_config = _load_config_public(config_path_p)
    protected_paths = {
        "source_population_db": source_db_p,
        "trading_calendar": trading_calendar_p,
        "background_news": news_pickle_p,
        "initial_beliefs": belief_csv_p,
    }
    protected_before = _protected_hashes(protected_paths)
    fixture_hash_before = sha256_file(fixture_db)

    base_summary: dict[str, Any] = {
        "banner": BANNER if execute_real_backend else DRY_BANNER,
        "phase": "9C",
        "gate_version": PHASE09C_VERSION,
        "formal_experiment_evidence": False,
        "mode": mode,
        "git": git,
        "population": {
            "size": POPULATION_SIZE,
            "population_seed": POPULATION_SEED,
            "selection_policy": "frozen Phase 3 deterministic bounded population builder",
            "fixture_db": str(fixture_db),
            "fixture_manifest": str(fixture_manifest),
            "population_ids": list(population_ids),
            "fixture_sha256": fixture_hash_before,
        },
        "activation": {
            "seed": ACTIVATION_SEED,
            "policy": "frozen Phase 4",
            "days": list(activation_plan),
            "expected_agent_pipeline_executions": sum(
                item["n_active"] for item in activation_plan
            ),
            "exact_backend_call_count": None,
            "exact_backend_call_count_note": (
                "one inherited Agent pipeline may make multiple backend calls; "
                "Phase 9C does not monkeypatch inference to count them"
            ),
        },
        "horizon": {
            "dates": list(fixed_dates()),
            "market_open": [item["market_open"] for item in day_plan],
            "fixed_three_calendar_days": True,
            "authoritative_calendar": str(trading_calendar_p),
        },
        "planned_days": day_plan,
        "api_config": public_config,
        "integrity": {
            "participant_data_used": False,
            "custom_market_logic_used": False,
            "custom_matching_used": False,
            "custom_price_formation_used": False,
            "structured_inference_instrumentation_used": False,
            "protected_sha256_before": protected_before,
        },
        "run_id": run_id,
    }

    if not execute_real_backend:
        protected_after = _protected_hashes(protected_paths)
        base_summary["integrity"].update(
            {
                "protected_sha256_after": protected_after,
                "protected_sources_unchanged": protected_before == protected_after,
                "generated_fixture_unchanged": fixture_hash_before == sha256_file(fixture_db),
            }
        )
        base_summary["status"] = "READY / 0 LLM / NO MARKET OR FORUM MUTATION"
        base_summary["duration_seconds"] = round(time.perf_counter() - start_time, 3)
        summary_path = run_dir / "summary.json"
        summary_path.write_text(
            json.dumps(base_summary, indent=2, ensure_ascii=False, default=str),
            encoding="utf-8",
        )
        base_summary["artifact"] = str(summary_path)
        return base_summary

    if not public_config["api_key_configured"]:
        raise Phase09CError("real-backend run requires api_key in config/api.yaml")

    from marketlens.agents.social.graph import build_bounded_social_graph
    from marketlens.agents.social.prominence import make_prominence_snapshot
    from marketlens.market.runtime.inherited_market import (
        advance_non_trading_day,
        advance_trading_day,
        reset_agent_world,
    )
    from marketlens.market.runtime.news import load_daily_news
    import simulation
    from util.ForumDB import (
        create_post_db,
        execute_forum_actions,
        get_all_users_posts_db,
        update_posts_score_by_date_range,
    )

    workspace_ctx = tempfile.TemporaryDirectory(prefix="marketlens_phase09c_n10_")
    workspace = Path(workspace_ctx.name)
    working_db = workspace / "runtime.db"
    forum_db = workspace / "forum.db"
    shutil.copy2(fixture_db, working_db)
    create_empty_forum_db(forum_db)

    reset_result = reset_agent_world(
        current_date=START_DATE.isoformat(),
        runtime_db=working_db,
        forum_db=forum_db,
        protected_paths=tuple(protected_paths.values()),
    )
    working_after_reset_sha = sha256_file(working_db)
    initial_beliefs = load_initial_beliefs(belief_csv_p, population_ids)

    real_days: list[dict[str, Any]] = []
    posts_created_total = 0
    forum_belief_agents_observed = 0
    later_day_forum_action_calls = 0
    previous_output_digest: str | None = None
    activation_chain_valid = True
    all_graphs_bounded_n10 = True

    try:
        for step, plan in enumerate(day_plan):
            date_str = str(plan["agent_world_date"])
            current_ts = pd.Timestamp(date_str)
            market_open = bool(plan["market_open"])
            batch = batches[step]
            active_ids = tuple(map(str, batch.active_agent_ids))
            activation_input_digest = activation_plan[step]["input_state_digest"]
            activation_output_digest = activation_plan[step]["output_state_digest"]
            if step > 0 and activation_input_digest != previous_output_digest:
                activation_chain_valid = False
            previous_output_digest = activation_output_digest

            graph_built = build_bounded_social_graph(
                runtime_db=working_db,
                history_cutoff=str(plan["history_cutoff"]),
                graph_start_date=GRAPH_START_DATE,
                similarity_threshold=SIMILARITY_THRESHOLD,
                time_decay_factor=TIME_DECAY_FACTOR,
            )
            prominence = make_prominence_snapshot(
                graph_built, top_fraction=TOP_FRACTION
            )
            top_user_ids = tuple(map(str, prominence.get("top_user_ids", ())))
            if graph_built.n_nodes != POPULATION_SIZE:
                all_graphs_bounded_n10 = False
            expected_top_n = max(1, int(POPULATION_SIZE * TOP_FRACTION))
            if len(top_user_ids) != expected_top_n:
                raise Phase09CError(
                    f"dynamic prominence returned {len(top_user_ids)} top users; "
                    f"expected {expected_top_n} for N10"
                )

            news_items = load_daily_news(news_pickle_p, current_date=date_str)
            df_stock, df_strategy = _load_runtime_frames(
                working_db, market_open=market_open
            )

            if step == 0:
                belief_args: Any = initial_beliefs
                belief_stats = {
                    "source": "initial_belief_csv",
                    "population": POPULATION_SIZE,
                    "forum_with_belief": 0,
                    "fallback_no_post": 0,
                    "fallback_missing_belief": 0,
                }
            else:
                belief_args, stats = build_forum_belief_args(
                    forum_db=forum_db,
                    current_date=current_ts,
                    initial_beliefs=initial_beliefs,
                    population_ids=population_ids,
                    forum_reader=get_all_users_posts_db,
                )
                forum_belief_agents_observed += stats["forum_with_belief"]
                belief_stats = {"source": "forum_with_initial_fallback", **stats}

            reasoning_started = time.perf_counter()
            agent_results = _execute_active_agents(
                process_user_input_fn=simulation.process_user_input,
                population_ids=population_ids,
                active_ids=active_ids,
                runtime_db=working_db,
                forum_db=forum_db,
                current_date=current_ts,
                day_1st=step == 0,
                graph=graph_built.graph,
                news_items=news_items,
                df_stock=df_stock,
                df_strategy=df_strategy,
                top_user_ids=top_user_ids,
                belief_args=belief_args,
                log_dir=run_dir,
                config_path=config_path_p,
                market_open=market_open,
            )
            reasoning_seconds = round(time.perf_counter() - reasoning_started, 3)

            records = write_daily_records(
                log_dir=run_dir,
                current_date=date_str,
                agent_results=agent_results,
            )
            post_stats = _create_posts(
                agent_results=agent_results,
                current_date=current_ts,
                forum_db=forum_db,
                create_post_fn=create_post_db,
            )
            posts_created_total += post_stats["created"]

            market_started = time.perf_counter()
            if market_open:
                market_result = advance_trading_day(
                    current_date=date_str,
                    runtime_db=working_db,
                    decision_json=records["trading_records"],
                    log_dir=run_dir,
                    protected_paths=tuple(protected_paths.values()),
                )
                market_action = "advance_trading_day"
            else:
                market_result = advance_non_trading_day(
                    current_date=date_str,
                    runtime_db=working_db,
                    protected_paths=tuple(protected_paths.values()),
                )
                market_action = "advance_non_trading_day"
            market_seconds = round(time.perf_counter() - market_started, 3)

            if step == 0:
                forum_action_stats = {
                    "attempted_user_calls": 0,
                    "successful_user_calls": 0,
                    "skipped_string_args": 0,
                    "score_update_invoked": False,
                }
            else:
                forum_action_stats = _apply_forum_actions(
                    agent_results=agent_results,
                    current_date=current_ts,
                    forum_db=forum_db,
                    execute_forum_actions_fn=execute_forum_actions,
                    update_scores_fn=update_posts_score_by_date_range,
                )
                later_day_forum_action_calls += forum_action_stats[
                    "successful_user_calls"
                ]

            runtime_metrics = capture_runtime_metrics(working_db, date_str)
            forum_metrics = capture_forum_metrics(forum_db)
            post_day_failures = _validate_runtime_day(
                metrics=runtime_metrics,
                market_open=market_open,
                population_size=POPULATION_SIZE,
            )
            conversation_dir = run_dir / "conversation_records" / date_str
            conversation_files = (
                len(list(conversation_dir.glob("*.json")))
                if conversation_dir.is_dir()
                else 0
            )

            real_days.append(
                {
                    **plan,
                    "activation": activation_plan[step],
                    "graph": {
                        "n_nodes": graph_built.n_nodes,
                        "n_edges": graph_built.n_edges,
                        "graph_sha256": graph_built.graph_sha256,
                        "history_cutoff": graph_built.history_cutoff,
                        "top_user_ids": list(top_user_ids),
                    },
                    "belief": belief_stats,
                    "reasoning": {
                        "active_agents": len(active_ids),
                        "attempted_agents": len(agent_results),
                        "failed_agents": 0,
                        "conversation_files": conversation_files,
                        "duration_seconds": reasoning_seconds,
                        "per_agent": [
                            {
                                "user_id": item["user_id"],
                                "duration_seconds": item["duration_seconds"],
                                "decision_result_present": item["decision_result"] is not None,
                                "post_response_present": item["post_response_args"] is not None,
                            }
                            for item in agent_results
                        ],
                    },
                    "records": records,
                    "posts": post_stats,
                    "market": {
                        "action": market_action,
                        "delegation_result": _serialize_result(market_result),
                        "duration_seconds": market_seconds,
                    },
                    "forum_actions": forum_action_stats,
                    "runtime_metrics": runtime_metrics,
                    "forum_metrics": forum_metrics,
                    "post_day_validation_failures": post_day_failures,
                }
            )

        protected_after = _protected_hashes(protected_paths)
        fixture_hash_after = sha256_file(fixture_db)
        base_summary.update(
            {
                "days": real_days,
                "reset": {
                    "delegation_result": _serialize_result(reset_result),
                    "working_runtime_sha256_after_reset": working_after_reset_sha,
                },
                "continuity": {
                    "activation_state_chain_valid": activation_chain_valid,
                    "all_graphs_bounded_n10": all_graphs_bounded_n10,
                    "same_working_runtime_across_all_days": True,
                    "same_working_forum_across_all_days": True,
                    "daily_graph_recomputed_after_prior_day_state": True,
                    "day2plus_belief_source": "inherited ForumDB with inherited initial-belief fallback",
                },
                "natural_multiday_coverage": {
                    "posts_created_total": posts_created_total,
                    "forum_belief_agents_observed": forum_belief_agents_observed,
                    "later_day_forum_action_calls": later_day_forum_action_calls,
                },
            }
        )
        base_summary["integrity"].update(
            {
                "protected_sha256_after": protected_after,
                "protected_sources_unchanged": protected_before == protected_after,
                "generated_fixture_sha256_after": fixture_hash_after,
                "generated_fixture_unchanged": fixture_hash_before == fixture_hash_after,
                "isolated_working_runtime_was_mutated": (
                    working_after_reset_sha != sha256_file(working_db)
                ),
                "participant_data_used": False,
                "custom_market_logic_used": False,
                "custom_matching_used": False,
                "custom_price_formation_used": False,
                "custom_agent_portfolio_update_used": False,
                "custom_tradingdetails_writer_used": False,
                "inherited_reasoning_entrypoint": "simulation.process_user_input",
                "inherited_trading_day_entrypoint": "marketlens.market.runtime.inherited_market.advance_trading_day",
                "inherited_non_trading_day_entrypoint": "marketlens.market.runtime.inherited_market.advance_non_trading_day",
                "inherited_forum_entrypoints": [
                    "util.ForumDB.get_all_users_posts_db",
                    "util.ForumDB.create_post_db",
                    "util.ForumDB.execute_forum_actions",
                    "util.ForumDB.update_posts_score_by_date_range",
                ],
            }
        )
        status, reasons = validate_real_summary(base_summary)
        base_summary["status"] = status
        base_summary["status_reasons"] = reasons
        base_summary["duration_seconds"] = round(time.perf_counter() - start_time, 3)
        summary_path = run_dir / "summary.json"
        summary_path.write_text(
            json.dumps(base_summary, indent=2, ensure_ascii=False, default=str),
            encoding="utf-8",
        )
        base_summary["artifact"] = str(summary_path)

        if status != "PASS" and preserve_workspace:
            debug_dir = run_dir / "failed_workspace"
            debug_dir.mkdir(parents=True, exist_ok=True)
            shutil.copy2(working_db, debug_dir / "runtime.db")
            shutil.copy2(forum_db, debug_dir / "forum.db")
            base_summary["failed_workspace"] = str(debug_dir)

        return base_summary
    finally:
        workspace_ctx.cleanup()
